spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/Ecommerce
    username: ecommerce_user
    password: ecommerce_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

external:
  products:
    base-url: https://dummyjson.com